version: '3.1'

services:

  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: jpress
       MYSQL_DATABASE: jpress
       MYSQL_USER: jpress
       MYSQL_PASSWORD: jpress

  jpress:
    depends_on:
      - db
    links:
      - db
    image: fuhai/jpress:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
       TZ: Asia/Shanghai
       JPRESS_DB_HOST: db
       JPRESS_DB_PORT: 3306
       JPRESS_DB_NAME: jpress
       JPRESS_DB_USER: jpress
       JPRESS_DB_PASSWORD: jpress

